name: Deploy

on:
    push:
        paths:
            - 'docs/**'
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: 18

            - uses: pnpm/action-setup@v2.2.4
              name: Install pnpm
              id: pnpm-install
              with:
                  version: 7
                  run_install: false

            - name: Install dependencies
              uses: covbot/pnpm-install-with-cache@v1

            - name: Build
              run: pnpm docs:build --base /${{ github.event.repository.name }}/

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: docs/.vitepress/dist
